name: Build All Dictionary Packs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  push:
    paths:
      - 'tools/**'
      - '.github/workflows/build-all-packs.yml'

permissions:
  contents: write
  
jobs:
  build-bilingual:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair: [eng-spa, spa-eng]  # Both directions for complete support
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip sqlite3 curl
        pip3 install pyglossary tqdm lxml
    
    - name: Build optimal bilingual pack
      run: |
        cd tools
        ./build-unified-pack.sh ${{ matrix.pair }}
    
    - name: List outputs (debug)
      run: |
        echo "PWD=$(pwd)"
        echo "Working directory after build:"
        pwd
        echo "Looking for files anywhere:"
        find . -name "${{ matrix.pair }}.*" -type f
        echo "Tools directory:"
        ls -la tools/dist/packs/ || echo "No tools/dist/packs/ directory"
        echo "Files in tools/dist/packs/:"
        ls -la tools/dist/packs/${{ matrix.pair }}.* || echo "No files match pattern"
    
    - name: Upload pack artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.pair }}
        path: tools/dist/packs/${{ matrix.pair }}.*
        if-no-files-found: error
        retention-days: 14


  publish-release:
    needs: [build-bilingual]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist/packs/
    
    - name: Flatten artifacts
      run: |
        mkdir -p final-packs
        echo "Downloaded artifacts structure:"
        ls -la dist/packs/ || echo "No dist/packs directory"
        find dist/packs/ -type f -name "*.zip" -exec cp {} final-packs/ \;
        find dist/packs/ -type f -name "*.json" -exec cp {} final-packs/ \;
        echo "Final packs contents:"
        ls -la final-packs/
    
    - name: Generate registry
      run: |
        cd final-packs
        python3 ../tools/generate-registry.py > registry.json
        cat registry.json
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: packs-${{ github.run_number }}
        name: Dictionary Packs v${{ github.run_number }}
        body: |
          Complete offline dictionary pack collection
          
          **BILINGUAL DICTIONARIES:**
          - eng-spa (4.6MB Wiktionary): English → Spanish - 43K+ entries
          - spa-eng (4.6MB Wiktionary): Spanish → English - 43K+ entries
          
          Built from: Wiktionary-Dictionaries ${{ github.sha }}
        files: |
          final-packs/*.zip
          final-packs/registry.json
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
