name: Build All Dictionary Packs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  push:
    paths:
      - 'tools/**'
      - '.github/workflows/build-all-packs.yml'

jobs:
  build-bilingual:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pair: [eng-spa, spa-eng]  # Focus on Spanish-English for testing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip sqlite3 curl
        pip3 install pyglossary tqdm lxml
    
    - name: Build optimal bilingual pack
      run: |
        cd tools
        ./build-unified-pack.sh ${{ matrix.pair }}
    
    - name: Upload pack artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.pair }}
        path: tools/dist/packs/${{ matrix.pair }}.*


  publish-release:
    needs: [build-bilingual]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist/packs/
    
    - name: Flatten artifacts
      run: |
        mkdir -p final-packs
        find dist/packs/ -name "*.zip" -exec cp {} final-packs/ \;
        find dist/packs/ -name "*.json" -exec cp {} final-packs/ \;
        ls -la final-packs/
    
    - name: Generate registry
      run: |
        cd final-packs
        python3 ../tools/generate-registry.py > registry.json
        cat registry.json
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: packs-${{ github.run_number }}
        name: Dictionary Packs v${{ github.run_number }}
        body: |
          Complete offline dictionary pack collection
          
          **BILINGUAL DICTIONARIES:**
          - eng-spa/spa-eng (4.6MB Wiktionary): English ↔ Spanish - 43K+ entries
          - eng-chn/chn-eng (4.6MB Wiktionary): English ↔ Mandarin - Full support
          
          **ADDITIONAL SUPPORTED LANGUAGES:**
          - eng-fra/fra-eng (3.2MB Wiktionary): English ↔ French
          - eng-deu/deu-eng (6.9MB Wiktionary): English ↔ German
          - eng-ita/ita-eng (5.3MB Wiktionary): English ↔ Italian
          - eng-por/por-eng (2.6MB Wiktionary): English ↔ Portuguese
          - eng-rus/rus-eng (4.2MB Wiktionary): English ↔ Russian
          - eng-kor/kor-eng (2.1MB Wiktionary): English ↔ Korean
          - eng-jpn/jpn-eng (5.9MB Wiktionary): English ↔ Japanese
          
          Built from: Wiktionary-Dictionaries ${{ github.sha }}
        files: |
          final-packs/*.zip
          final-packs/registry.json
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}